site_name: Kappa - OpenAPI library for Java
repo_url: https://github.com/erosb/kappa
repo_name: Kappa
theme:
  name: material
  icon:
    annotation: material/arrow-right-circle-outline
  color_mode: dark
  palette:
    scheme: slate
    primary: black
    accent: light blue
  features:
    - content.code.annotate
    - content.code.copy
markdown_extensions:
  - toc:
      permalink: true
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  # - md_in_html
  # - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - 'Welcome to Kappa': 'index.md'
  - 'Spring Boot':
      - 'spring-boot/contract-testing.md'
      - 'spring-boot/request-validation.md'
  - 'Other frameworks':
      - 'Servlet API': other-frameworks/servlet-api.md
      - 'Undertow': other-frameworks/undertow.md
      - 'Vert.x': other-frameworks/vertx.md
extra:
  kappa_version: 2.0.0-RC16
  analytics:
    provider: google
    property: G-ETPR43KXJH
plugins:
  - macros
